basePath: /
definitions:
  server.Req:
    properties:
      options:
        additionalProperties: true
        type: object
      url:
        type: string
    type: object
  server.Res:
    properties:
      code:
        type: integer
      data:
        additionalProperties: true
        type: object
      msg:
        type: string
    type: object
host: localhost:6664
info:
  contact: {}
  description: This is a dalfox api swagger
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: DalFox API
  version: "1.0"
paths:
  /scan:
    post:
      consumes:
      - application/json
      description: add dalfox scan
      parameters:
      - description: json data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/server.Req'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Res'
      summary: scan
swagger: "2.0"
